const String p1 =
    "Murabbiy sportchi organizmini tiklash uchun organizmiga ta'sir korsatuvchi yagona funksional tizim yaratishi lozim. Bunda unga kerak bolgan barcha tashqi va ichki omillardan foydalaniladi aks holda ularni boshqa funksional tizimlarga ta'sir ko'rsatishi mumkin. Barcha harakatlar aniq bir natijaga erishishga qaratilgan bo'lishi lozim. Bu holda sport natijalarini keyinchalik o'sish ta'sir kuchlari yig'indisining ortishi (moslashuv tizimi buzilish xavfi ostida qoladi), yoki yuqori samaradorlik organizmning yashash sharoitlarini ko'p darajada (bu holda, birinchi navbatda ichki) vositalar (farmakologik, fizioterapevtik) ni qo'llash yordamida ish qobilyatini oshirish hozirgi kunda ko'pchilik holatlarda sport mashg'ulotlarini tashkil qilish shu qoidalarga asoslanib amalga oshirilmoqda. Bundan ko'zlangan maqsad esa faqatgina yuqori malakali sportchilarni emas, balki har tomonlama jismoniy rivojlangan sportchilar shakllantirishdir.";
const String p2 =
    "Mashg'ulotdan so'ng barcha tana tizimlari uchun tiklovchi vositalarni qo'llashga muhim ahamiyat qaratish zarur hisoblanadi. Unda psixologik holatini tiklash uachun quyidagi vositalar ishlatiladi: gidroterapiya (issiq hammom, issiq dush, tuz vannalar), moylar, bug' hammomi, B vitaminlari va psixoterapiyalarning o'rni muhimdir.";
const String p3 =
    "Sportchilar faoliyatini tiklash uchun jismoniy omillardan foydalanishda sog'lomlashtirish tadbirlarining asosini organizmga umumiy ta'sir etuvchi vositalar tashkil etadi. Umumiy ta'sirning fizioterapiya muolajalari: vannalar, elektromuolajalar, bug' va quruq havo hammomlari samarali hisoblanadi.";
const String p4 =
    " Jismoniy omillar murakkab bo'lsada, foydali tomolaridan biri tananing reseptor zonalari markaziy asab tizimi (teri, nafas olish) orqali harakat qiladi. Ularni tiklash mexanizmi ortib borishi bilan izohlanadi. Metabolik jarayonlar, limfa tugunlarida qonning me'yorda aylanishi, kisloroddan foydalanish va parchalanish jarayonini taminlab beradi. Ular tananing avtonom tizimlari va markaziy asab tizimining vazifalari charchoqlarni bartaraf etish, organizmning immunobiologik holatini oshirish va ishlashiga ijobiy ta'sir ko'rsatadi. Tiklanish tadbirlari tabaqalashtirilgan holda amalga oshirilishi kerak. Bunda quyidagi omillarga ahamiyat qaratish zarur.";
const String p5 =
    "Har bir sportchi o'z sog'lig'ini har kuni nazorat qilishi lozim vujudga keladigan tiklovchi mashqlar va boshqa sabablarga ko'ra organizmdagi buzilishlarni o'z vaqtida aniqlash zarur, bu esa funksional imkoniyatlarini oshiradi. Jismoniy faoliyatda sportchi, o'quv mashg'ulotlari og'riqli holatda yoki tiklanish bosqichi, rejimning buzilishi o'tkir rivojlanishiga yoki ortiqcha surunkali jismoniy zo'riqishga olib kelishi mumkin. Sportchi salomatligiga yana bir xavf tayanch harakat apparatiga noto'g'ri ta'sir ko'rsatishdir. Shu munosabat bilan tiklanish (massaj, vanna) vositalariga katta e'tibor qaratiladi. Massaj bilan birgalikda vanna kompensator rolni bajaradi, u avtonom asab tizimi va mushaklarni bo'shashtirishga yordam beradi. Hammom qabul qilish jarayonida bir-birining o'rnini bosadigan massaj xususiyati (bug' xonasi, dush, kontrast vannalar, hovuz, massaj, va hokazo.), tizimlariga maxsus mashq qo'llash qon aylanishini, issiqlik almashinuvini tartibga solishda samarali hisoblanadi. Shuning uchun tajribalar davomida vanna qabul qilishning tartibli majmuasidan so'ng organizm tiklanadi va voleybolchilarning ish qobiliyati oshadi hamda kasalliklar bilan kasallanish keskin kamayadi. ";
const String p7 =
    "Tiklovchi vositalarning mashg'ulot jarayonining turli darajalarida samarali taqsimlanishi ko'p jihatdan sportchilarning jismoniy tayyorgarligini yaxshilash va yuqori sport natijalariga erishishni belgilaydi. Bugungi kunda organizmning tiklovchi vositalari turli xil mexanizmlari bo'yicha amalga oshiriladi. Sportchilarni tayyorlashda asosiy o'rinni turli texnologiyalar, vositalar, sog'lomlashtirish usullari va ish faoliyatini takomillashtirish omillarini o'z ichiga oladi. Sportchilar organizmida tiklanish jarayonlari eng muhim psixofiziologik jarayon bo'lib, uning mexanizmi mushak faoliyatidan keyin yuqori shiddatdagi jismoniy faoliyatni ta'minlaydigan funksional tizimlar ishida o'zgarishlar sodir bo'ladi. Mashg'ulot yuklamalaridan so'ng tiklanish organizmning asliga yoki unga yaqin darajaga qaytishini bildirmaydi.";
const String p8 =
    "Charchash va tiklanish jarayonlarining optimal kombinatsiyasi organizmning jismoniy zo'riqishga doimiy va uzoq muddatli moslashishining fiziologik asosi hisoblanadi. Shuning uchun mashg'ulot va musobaqa yuklamalaridan so'ng turli tiklovchi vosita va usullardan foydalanish sportchilarni tayyorlashning muhim qismi hisoblanadi. ";
const String p9 =
    "Baland tog'li xududlarda oquv-yigin mashg'ulot olib borishning omillari.";
const String p10 =
    "Malakali voleybolchi qizlarni tayyorgalik jarayonini asosan tog'li hududlarda olib borilganda, sportchilar tanasiga qo'shimcha yuklama berib boriladi  asta sekin moslashib boradi. Dengiz sathidan 1500 m yuqorida mashg'ulotlar jarayoni olib borish takrorlanadi. Balandlikda atrofidagi muhitning bosimi kamayadi, shuning bilan birga o'pka oladigan kislorod hajmi ham kamayadi; Tog' muhitidagi havo kislorod bilan uncha to'yinmagan bo'ladi. Bu yangi, tog' balandlik muhitga mashg'ulotlar jarayonida odam tanasi yurak-qon tizimining kislorodni tejamkor iste'mol qilish hisobiga moslashadi. Baland tog joylarida sekinroq yugurilsa ham odamning havo olishi tezlashadi. Muhitga moslashgan (adaptatsiya)dan so'ng hamma odam tanasi o'z holatiga keladi. Bu moslashish tufayli, oldingi muhitga qaytgandan keyin sportchining jismoniy tayyorgarlik ko'rsatkichlari dastlabki 2-3 kun yuqori bo'ladi. Shuning uchun, ko'pgina sportchilar baland tog'li xududlarda mashg'ulotlar rejalashtiradi va amalga oshiriladi. Yuqorida aytilgan pedagogik, tibbiy-biologik, psixologik iklovchi vositalar orqali balandlik faktori ta'sirida amalga oshirilsa mashg'ulotlar jarayonini yanada samarador ekanligi aniqlandi.  YuQS o'zgarishiga qarab tiklovchi yositalar qo'llaniladi. Organizmni tiklashda, sportchi yurak-qon tomir tizimi doimiy ravishda nazorat qilib boriladi. Chunki, organizmga shiddatli mashg'ulotlar ta'sirida yurakka juda yuqori yuklamalar tushadi. ";
const String p11 =
    "Bunga ko'pincha sportchilar uncha e'tibor bermaydilar. Shamollash kasalligidan keyin 3-5 kun sport yuklamalarini pasaytirish va nazorat ostida ularni asta-sekinlik bilan oshirish tavsiya etiladi. Sifatli ovqatlanish, vitaminlar, tuzlar va suvlar balansini tiklash, vanna, dush, tinchlantiruvchi massaj qon tomir urishi doirasi tiklanishiga ancha hissa qo'shadi. Tiklanish vositalariga, quyida keltirgan tadbirlar oddiy va uncha murakkab emas, shuning uchun yuqorida aytilganlar qo'llanilsa, sportchi ozini ancha yengil va tetik his qiladi.";
const String p12 =
    "Barcha tiklovchi vositalardan foydalanishning optimal shakli ulardan bir nechtasini bitta murakkab tartibda ketma-ket yoki parallel qo'llashdan iborat. Bunday yondashuv ularning maxsus yo'naltirilgan ta'sirini o'zaro mustahkamlanishi tufayli bir necha dori vositalarining umumiy samaradorligini oshiradi. Mashg'ulotlarda ish qobiliyatini boshqarish vositalariga yoki uaning bir qismiga ta'sir ko'rsatilmaydi, lekin bir vaqtning ozida keyingi mashg'ulotlarda tiklovchi komponentlarni tanlab qo'llash kiradi. Ertalabki mashg'ulotda tezlik qobiliyatlarini rivojlantirishga qaratilgan bo'lsa, ikkinchi yarimida anaerob (glikolitik) xarakterdagi chidamlilik bo'lsa. Birinchi mashg'ulotdan so'ng bu turdagi chidamlilikni namoyon qilishga tez tiklanish imkoniyatlarini yordam beruvchi vositalar toplamini qo'llash o'rinli bo'ladi. Bu esa ikkinchi mashg'ulotdagi yuklamaning sifatini yaxshilaydi va hajmini oshiradi. Xulosa o'rida, mushak faoliyatlariga yuklama ta'siri natijasida, charchash darajasi namoyon boladi. Charchoq fiziologik xavfsizlik mexanizmi organizmni haddan tashqari zoriqishdan himoya qiladi va shu bilan birga organizmni tez moslashishiga yordam beradi. Natijada, sportchilarning jismoniy qobiliyatlari rivojlanadi hamda ish qobiliyati oshadi. ";
const String p13 =
    "Tiklanish jarayonlarining jadalligi va organizmning energiya zaxiralarini to'ldirish vaqti mashqlar davomida ularning sarflanish jadalligigi bilan bog'liq jarayondir. Organizmni tiklanish jarayonlarining tezlashishi mashg'ulotdan keyin ma'lum dam olish oralig'ida energetik moddalar zaxiralarining oldindan ishlash darajasidan oshib ketishiga olib keladi. Bu hodisa superkompensatsiya yoki to'liq-tiklanish deb ataladi. Superkompensatsiya fazasining vaqt bo'yicha uzunligi mashg'ulotning umumiy davomiyligiga va organizmda kelib chiqadigan biokimyoviy ozgarishlarning darajasiga bog'liq. Tiklanish jarayonlarining tabiatini belgilovchi muhim omil bu sportchining yosh xususiyati hisoblanadi. Shuningdek faol dam olish sportchi organizmini tiklash va uning jismoniy tayyorgarligini saqlab turishning Afzal usullaridan biri hisoblanadi. ";
